// <auto-generated />
using System;
using Lisan.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lisan.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524205944_AddTranscriptsTable")]
    partial class AddTranscriptsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lisan.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_profile_id");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<int>("PersianWordsProducedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("persian_words_produced_count");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("persona_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("StoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("story_id");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId")
                        .HasDatabaseName("ix_sessions_child_profile_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_sessions_status");

                    b.HasIndex("Status", "LastActivityAt")
                        .HasDatabaseName("ix_sessions_status_last_activity_at");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Lisan.Domain.Entities.Transcript", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Speaker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("speaker");

                    b.Property<string>("TextFa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_fa");

                    b.Property<int>("Turn")
                        .HasColumnType("integer")
                        .HasColumnName("turn");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_transcripts_session_id");

                    b.ToTable("transcripts", (string)null);
                });

            modelBuilder.Entity("Lisan.Domain.Entities.Transcript", b =>
                {
                    b.HasOne("Lisan.Domain.Entities.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_transcripts_sessions_session_id");
                });
#pragma warning restore 612, 618
        }
    }
}
