// <auto-generated />
using System;
using Lisan.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lisan.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530225852_AddParentAndChildProfile")]
    partial class AddParentAndChildProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lisan.Domain.Entities.ChildProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivePersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_persona_id");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DailyTimeLimitMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("daily_time_limit_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<int>("SessionsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sessions_completed");

                    b.Property<int>("SpeakingLadderStage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("speaking_ladder_stage");

                    b.HasKey("Id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_child_profiles_parent_id");

                    b.ToTable("child_profiles", (string)null);
                });

            modelBuilder.Entity("Lisan.Domain.Entities.Parent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ClerkUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clerk_user_id");

                    b.Property<DateTimeOffset?>("ConsentAcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consent_accepted_at");

                    b.Property<string>("ConsentVersion")
                        .HasColumnType("text")
                        .HasColumnName("consent_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.HasKey("Id");

                    b.HasIndex("ClerkUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_parents_clerk_user_id");

                    b.ToTable("parents", (string)null);
                });

            modelBuilder.Entity("Lisan.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_profile_id");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<int>("PersianWordsProducedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("persian_words_produced_count");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("persona_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("StoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("story_id");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId")
                        .HasDatabaseName("ix_sessions_child_profile_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_sessions_status");

                    b.HasIndex("Status", "LastActivityAt")
                        .HasDatabaseName("ix_sessions_status_last_activity_at");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Lisan.Domain.Entities.Transcript", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Speaker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("speaker");

                    b.Property<string>("TextFa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_fa");

                    b.Property<int>("Turn")
                        .HasColumnType("integer")
                        .HasColumnName("turn");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_transcripts_session_id");

                    b.ToTable("transcripts", (string)null);
                });

            modelBuilder.Entity("Lisan.Domain.Entities.ChildProfile", b =>
                {
                    b.HasOne("Lisan.Domain.Entities.Parent", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_child_profiles_parents_parent_id");
                });

            modelBuilder.Entity("Lisan.Domain.Entities.Session", b =>
                {
                    b.HasOne("Lisan.Domain.Entities.ChildProfile", null)
                        .WithMany()
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_sessions_child_profiles_child_profile_id");
                });

            modelBuilder.Entity("Lisan.Domain.Entities.Transcript", b =>
                {
                    b.HasOne("Lisan.Domain.Entities.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_transcripts_sessions_session_id");
                });
#pragma warning restore 612, 618
        }
    }
}
